name: Tests
on: 
  push:
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && export DEBIAN_FRONTEND=noninteractive
          sudo apt-get -y install --no-install-recommends jq curl shellcheck file

      - name: Run tests
        run: ./tests.sh